//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DCSoft.Demo.Model
{

	/// <summary>
	/// 实体类ST_USER 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ST_USER")]
	[Serializable]
	public partial class ST_USER : Entity 
	{
		#region Model
		private string _userName;
		private string _passWord;
		private int? _age;
		private bool? _sex;
		private string _address;
		private string _comment;
		private string _trueName;
		/// <summary>
		/// 
		/// </summary>
		public string userName
		{
			get{ return _userName; }
			set
			{
				this.OnPropertyValueChange(_.userName,_userName,value);
				this._userName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string passWord
		{
			get{ return _passWord; }
			set
			{
				this.OnPropertyValueChange(_.passWord,_passWord,value);
				this._passWord=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? age
		{
			get{ return _age; }
			set
			{
				this.OnPropertyValueChange(_.age,_age,value);
				this._age=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? sex
		{
			get{ return _sex; }
			set
			{
				this.OnPropertyValueChange(_.sex,_sex,value);
				this._sex=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string address
		{
			get{ return _address; }
			set
			{
				this.OnPropertyValueChange(_.address,_address,value);
				this._address=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string comment
		{
			get{ return _comment; }
			set
			{
				this.OnPropertyValueChange(_.comment,_comment,value);
				this._comment=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string trueName
		{
			get{ return _trueName; }
			set
			{
				this.OnPropertyValueChange(_.trueName,_trueName,value);
				this._trueName=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.userName};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.userName,
				_.passWord,
				_.age,
				_.sex,
				_.address,
				_.comment,
				_.trueName};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._userName,
				this._passWord,
				this._age,
				this._sex,
				this._address,
				this._comment,
				this._trueName};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ST_USER");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field userName = new Field("userName","ST_USER","userName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field passWord = new Field("passWord","ST_USER","passWord");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field age = new Field("age","ST_USER","age");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sex = new Field("sex","ST_USER","sex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field address = new Field("address","ST_USER","address");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field comment = new Field("comment","ST_USER","comment");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field trueName = new Field("trueName","ST_USER","trueName");
		}
		#endregion


	}
}

